# Generated by Django 3.1.1 on 2020-09-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
